import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { GetServerSideProps } from "next";
import { csv } from "d3-fetch";
import React from "react";
import { Container, Title, Text } from "@mantine/core";
import CaseList from "../components/CaseList";

const Home: NextPage = ({ data }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <div>
            <Title order={1}>Polizeiliche Todesschüsse</Title>
            <Title order={3}>This is h2 title</Title>
            <Text size="md">
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi
              impedit neque odio rem voluptatibus quas quisquam quia blanditiis
              deleniti ad accusamus quaerat, recusandae cum eum tenetur minima
              inventore incidunt temporibus?
            </Text>
          </div>
          <CaseList data={data} />
        </Container>
      </main>

      <footer></footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  let url = "http://localhost:3000/data.csv";
  if (process.env.NODE_ENV === "production")
    url = "http://cilip.app.vis.one/data.csv";

  const data = await csv(url);

  return { props: { data } };
};

export default Home;
